---
#
# Ansible playbook: Webmin for Ubuntu v201501302302
# Martin Georgiev
# martingeorgiev.com
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/fail2ban.yml --extra-vars 'target=nameFromHostsFile'
#
- hosts: '{{ target }}'
  sudo: yes

  tasks:

     - name: Install fail2ban and dependancies
       apt: >
        update_cache=yes
        pkg={{ item }}
        state=installed
       with_items:
         - whois
         - python3-pyinotify
         - fail2ban
