---

- hosts: kali
  vars:
    users:
    - ansible
  tasks:
    - name: Print the users
      ansible.builtin.debug:
        msg: The folloing users will be created {{ item }}
      with_items: "{{ users }}"

    - name: Perform full patching
      package:
        name: '*'
        state: latest

    - name: Add ansible group
      group:
        name: "{{ item }}"
        state: present
      with_items: "{{ users }}"

    - name: Add local user
      user:
        name: ansible
        group: ansible
        shell: /bin/bash
        home: /home/ansible
        create_home: yes
        state: present

    - name: Add local user
      user:
        name: "{{ users }}"
        group: "{{ users }}"
        shell: /bin/bash
        home: "/home/{{ item }}"
        create_home: yes
        state: present
      with_items: "{{ users }}"

    - name: Add SSH public key for user
      authorized_key:
        user: "{{ users }}"
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      with_items: "{{ users }}"

    - name: Add sudoer rule for local user
      copy:
        dest: /etc/sudoers.d/"{{ item }}"
        src: etc/sudoers.d/"{{ item }}"
        owner: root
        group: root
        mode: 0440
        validate: /usr/sbin/visudo -csf %s
      with_items: "{{ users }}"

    - name: Add hardened SSH config
      copy:
        dest: /etc/ssh/sshd_config
        src: etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0600
      notify: Reload SSH

  handlers:
    - name: Reload SSH
      service:
        name: sshd
        state: reloaded