# https://www.redhat.com/sysadmin/ansible-create-users-csv
---
- hosts: users
  tasks:

  vars:
    users:
    - ansible
  vars_prompt:
  - name: "user_password"    
    prompt: "Enter a password for the user"
    private: yes    
    encrypt: "md5_crypt" #need to have python-passlib installed in local machine before we can use it    
    confirm: yes    
    salt_size: 7

  - name: Add several users
    ansible.builtin.user:
      name: "{{item}}"
      password: "{{user_password}}"
      state: present
      groups: "wheel"
      update_password: on_create
    with_items: "{{ users }}"

  # - name: Creating user "{{ uusername }}" with admin access
  #   user: 
  #     name: {{ uusername }}
  #     password: {{ upassword | password_hash('sha512') }}
  #     groups: admin append=yes
  #   when:  assigned_role  == "yes"

  # - name: Creating users "{{ uusername }}" without admin access
  #   user:
  #     name: {{ uusername }}
  #     password: {{ upassword | password_hash('sha512') }}
  #   when:  assigned_role == "no"

  # - name: Expiring password for user "{{ uusername }}"
  #   shell: chage -d 0 "{{ uusername }}"
  
  # - name: "add new user"
  #   user: 
  #       name="{{user_name}}"
  #       comment="{{description_user}}"
  #       password="{{user_password}}"
  #       home="{{home_dir}}"
  #       shell="/bin/bash
  #       update_password=on_create