---
#
# Ansible playbook: Webmin for Ubuntu v20211051514
# Martin Georgiev
# martingeorgiev.com
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/fail2ban.yml --extra-vars 'target=nameFromHostsFile'
#
  - hosts: '{{ target }}'
    become: true

    tasks:
      - name: Install aptitude using apt
        apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

      - name: Add Docker GPG apt Key
        apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present

      - name: Install docker and dependancies
        apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
        loop: [ 'whois' , 'python3-pyinotify', 'fail2ban' ]

      - name: Install required system packages
        apt: name={{ item }} state=latest update_cache=yes
        loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

      - name: Add Docker Repository
        apt_repository:
          repo: deb https://download.docker.com/linux/ubuntu bionic stable
          state: present

      - name: Update apt and install docker-ce
        apt: update_cache=yes name=docker-ce state=latest

      - name: Install Docker Module for Python
        pip:
          name: docker

      # - name: Pull default Docker image
      #   docker_image:
      #     name: "{{ default_container_image }}"
      #     source: pull

      # # Creates the number of containers defined by the variable create_containers, using values from vars file
      # - name: Create default containers
      #   docker_container:
      #     name: "{{ default_container_name }}{{ item }}"
      #     image: "{{ default_container_image }}"
      #     command: "{{ default_container_command }}"
      #     state: present
      #   with_sequence: count={{ create_containers }}