# sudo service telegraf start

# sudo service telegraf status
# telegraf -config /etc/telegraf/telegraf.conf -test
---
- hosts: telegraf
  become: true
  become_user: root
  tasks:
    - name: Telegraf repository key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        keyring: /etc/apt/trusted.gpg.d/telegraf.gpg
        state: present

    - name: Telegraf repository
      apt_repository:
        repo: "deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: telegraf
      register: repo_telegraf 
    
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
    
    - name: Install apache telegraf  (state=present is optional)
      apt:
        name: telegraf
        state: present
    
    - name: Start service telegraf, if not started
      ansible.builtin.service:
        name: telegraf
        state: started