---
create_user: ansible
upassword: Passw0rd!
copy_local_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
sys_packages: [ 'curl', 'nano', 'git', 'ufw', 'whois' , 'python3-pyinotify', 'fail2ban']
