---
#
# Ansible playbook: Webmin for Ubuntu v201501302302
# Louis T. Getterman IV (@LTGIV)
# www.GotGetLLC.com / www.opensour.cc
#
# Example Usage:
# [user@host ~$] ansible-playbook /etc/ansible/playbooks/webmin.yml --extra-vars 'target=nameFromHostsFile'
#
- hosts: '{{ target }}'
  become: true
  become_user: root

  tasks:

     - name: Add Webmin repositories
       apt_repository: >
        repo='{{ item }}'
        state=present
       with_items:
         - 'deb http://download.webmin.com/download/repository sarge contrib'
         - 'deb http://webmin.mirror.somersettechsolutions.co.uk/repository sarge contrib'

     - name: Add Webmin key
       apt_key: >
        url='http://www.webmin.com/jcameron-key.asc'
        state=present

     - name: Install Webmin and prerequisites
       apt:
        state: present
        autoclean: yes
        #update_cache=yes
        update_cache: yes
        pkg: [
          "perl",
          "libnet-ssleay-perl",
          "openssl",
          "libauthen-pam-perl",
          "libpam-runtime",
          "libio-pty-perl",
          "apt-show-versions",
          "python",
          "webmin"
          ]
